print("Hello dear! May I ask your name?")
name = input()
print("What a cute name " + name)
print("How old are you?")
age = int(input())
print ("What is your FavoriteFood")
favoriteFood = input()
print("oh! What a delicous foods")
print("Who is your favoriteCartoonCharacter")
favoriteCartoonCharacter = input()
print("i miss her.")